version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    image: your-dockerhub-username/nextjs-app:latest
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/app/logs